name: C++ and Python Tests

on:
  push:
    branches:    
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!main'   # excludes master
  pull_request:
    branches:    
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!main'   # excludes master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Python dependencies
      run: python -m pip install --upgrade pip

    - name: Check Python syntax
      run: |
        find . -name "*.py" -exec sh -c 'python -m py_compile {} && exit $?' \;

    - name: Run Python tests
      run: |
        find . -type d -name "python" -exec sh -c 'cd "$0" && python -m unittest discover && exit $?' {} \;

    - name: Install C++ dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++ libgtest-dev

    - name: Check C++ syntax
      run: |
        find . -name "*.cpp" -exec sh -c 'g++ -fsyntax-only -std=c++11 -o /dev/null -S "$0" && exit $?' {} \;

    - name: Build and run C++ tests
      run: |
        find . -type d -name "cpp" -exec sh -c 'cd "$0" && mkdir -p build && cd build && cmake .. && make && ./mytests && exit $?' {} \;
