name: C++ and Python Tests

on:
  push:
    branches:    
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!main'   # excludes master
  pull_request:
    branches:    
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!main'   # excludes master

jobs:
  python_syntax_check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Python dependencies
      run: python -m pip install --upgrade pip
    - name: Check Python syntax
      run: |
        find . -name "*.py" -print0 | while IFS= read -r -d '' file; do
          python -m py_compile "$file" || exit 1
        done
  python_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Python dependencies
      run: python -m pip install --upgrade pip
    - name: Run Python tests
      run: |
        find . -type d -name "python" -print0 | while IFS= read -r -d '' dir; do
          cd "$dir" && python -m unittest discover || exit 1
        done